// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgI07JC2q9CIoHqjdlVfk2F7YI-SdJO24',
    appId: '1:63476213036:web:8afed9c95c4d3cce94f889',
    messagingSenderId: '63476213036',
    projectId: 'machinetest-863cb',
    authDomain: 'machinetest-863cb.firebaseapp.com',
    storageBucket: 'machinetest-863cb.appspot.com',
    measurementId: 'G-MJ2YZQ04CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAaDhIHWkZSMHXQqjgbVI_ihMAsmCp5_U',
    appId: '1:63476213036:android:902528affc1c440794f889',
    messagingSenderId: '63476213036',
    projectId: 'machinetest-863cb',
    storageBucket: 'machinetest-863cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DefofNG9WO9phDvTxT9AqsV3ho5dEjE',
    appId: '1:63476213036:ios:8dd85c11cd83b6d394f889',
    messagingSenderId: '63476213036',
    projectId: 'machinetest-863cb',
    storageBucket: 'machinetest-863cb.appspot.com',
    iosClientId: '63476213036-dn3e5gtqp12dfvqbr1dplljehi60nibh.apps.googleusercontent.com',
    iosBundleId: 'com.example.machineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6DefofNG9WO9phDvTxT9AqsV3ho5dEjE',
    appId: '1:63476213036:ios:8dd85c11cd83b6d394f889',
    messagingSenderId: '63476213036',
    projectId: 'machinetest-863cb',
    storageBucket: 'machinetest-863cb.appspot.com',
    iosClientId: '63476213036-dn3e5gtqp12dfvqbr1dplljehi60nibh.apps.googleusercontent.com',
    iosBundleId: 'com.example.machineTest',
  );
}
